import type { Metadata } from 'next';
import { Rubik } from 'next/font/google';
import { Navbar } from '../components/navbar';
import TanstackQueryProvider from '../providers/tanstack-query-provider';
import './globals.css';

const rubik = Rubik({
  subsets: ['latin'],
  display: 'swap',
  weight: ['300', '400', '500', '600', '700'],
  variable: '--font-rubik',
});

export const metadata: Metadata = {
  title: 'Cirkle',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={rubik.variable}>
      <body
        className="font-rubik text-white antialiased bg-[#0A0A0A] min-h-screen overflow-y-scroll"
        style={{
          margin: 0,
          padding: 0,
          overflowY: 'scroll', // 👈 ensures scrollbar always reserved
          scrollbarGutter: 'stable both-edges', // 👈 modern fix for layout shift
        }}
      >
        <TanstackQueryProvider>
          <div className="w-full max-w-screen-xl mx-auto px-5 sm:px-5 md:px-8 lg:px-10 xl:px-20 2xl:px-20 py-5 space-y-2">
            <Navbar />
            <div className="w-full">{children}</div>
          </div>
        </TanstackQueryProvider>
      </body>
    </html>
  );
}
